### ISSUE TITLE
Replace Tox test suite with an alternative

### ISSUE THREAD

**Issue by Archmonger** [Archmonger/ServeStatic#17]
### Description

Tox is a bit of a nightmare to work with it's fiddly configuration files, so we should switch to that when possible.

**Comment by stumpylog** [comment]
You might consider something like `hatch` as well.  All configured via `pyproject.toml`, it can use matrices to provide a full replacement of tox, while also handling building sdist and wheels.  Just a thought.

Thanks for the fork, I'm looking into using it over whitenoise.
