### ISSUE TITLE
Replace `flake8/isort/black` with `ruff`

### ISSUE THREAD

**Issue by Archmonger** [Archmonger/ServeStatic#33]
### Description

We currently use `flake8/isort/black` since that was what our upstream (`WhiteNoise`) uses, but we should replace it with the more sane/performant `ruff` linter when possible.

**Comment by stumpylog** [comment]
Since `hatch` is in now, ruff linting and formatting is basically built in with `hatch fmt` and `hatch fmt --check`.  And since ruff follows pyproject configuration, easy to configure it fully there or accept the hatch defaults.

**Comment by Archmonger** [comment]
As a note, I'd like resolving this ticket to involve a [VsCode profile](https://code.visualstudio.com/docs/editor/profiles) and [editor.config](https://editorconfig.org/) file with sane defaults.
